"""
Script that carries out Bayesian optimisation of filter thicknesses for synthetic
images generated by the custom implementation.

Optimises 6 proton filters using 3 electron filters obtained from custom_electron_op.py

"""

import os
import numpy as np
import optuna
import pickle

from typing import Any, Dict, List
import optuna
from machine_learning.keras_trial import ml_trial
import custom.filter as fil
import custom.generation as dg
import utils

# Get the current directory path
current_file_path = os.path.abspath(__file__)
current_dir = os.path.dirname(current_file_path)

best_images_and_labels_path = (
    f"{current_dir}/../output/synthetic_images/new_custom_op_electrons_filters_jan18.pickle"
)
best_model_path = f"{current_dir}/../output/nn_models/new_custom_op_electrons_filters_model_jan18.keras"
study_db_path = f"{current_dir}/../output/optuna_studies/new_custom_op_electrons_filters_jan18.db"
study_name = "op-filters"


N_IMAGES = 5000
N_WORKERS = 120
TIMEOUT = 20 * 60 * 60
ADD_ELECTRONS = True

# Image properties
N_FILTERS = 6
E_MAX_BNDS = (0.1, 5)
T_P_BNDS = (0.05, 2)
N_PARTICLE_BNDS = (1e7, 1e10)
N_MACROPARTICLES = int(1e5)

electron_filter_thickness_1 = 1
electron_filter_thickness_2 = 2
electron_filter_thickness_3 = 3


def generate_data(trial: optuna.Trial) -> Dict[str, List]:
    """
    Optimisation of filter attributes.
    y = a*b**x
    """
    # Trialing a set of unique filter thicknesses
    #filter1 = trial.suggest_float("filter1", 2.8094e-5, 1e-2)
    #filter2 = trial.suggest_float("filter2", 2.8094e-5, 1e-2)
    #filter3 = trial.suggest_float("filter3", 2.8094e-5, 1e-2)


    a = trial.suggest_float("a", 0, 2e-4)
    #a = 2e-4
    #b = 1
    b = trial.suggest_float("b", 0, 1)

    LOWER_BND = 1e-7

    filter_array = utils.exponential_dist(a, b, np.arange(N_FILTERS))
    filter_array = utils.set_lower_bnd(filter_array, LOWER_BND)
    trial.set_user_attr("filter_thicknesses", filter_array.tolist())

    # Filter

    # Using 6 filters from proton filters and manually adjusting other 3 to optimse for electrons
    # Fitting 3 electron filters using exponential distribution

    base_unit = [
        [electron_filter_thickness_1, electron_filter_thickness_2, electron_filter_thickness_3],
        [filter_array[0], filter_array[1], filter_array[2]], 
        [filter_array[3],filter_array[4], filter_array[5]],
    ]
    filter = fil.Filter(base_unit, 10, (1, 1))

    # Generating the data
    images_and_labels = dg.gen_many_parallel(
        E_MAX_BNDS,
        T_P_BNDS,
        N_PARTICLE_BNDS,
        N_MACROPARTICLES,
        np.array(filter.filter),
        filter.map,
        N_IMAGES,
        N_WORKERS,
        add_electrons=ADD_ELECTRONS,
    )
    return images_and_labels



def objective(trial: optuna.Trial, best_attributes: Dict[str, Any]) -> float:

    # Tracking best trial attributes
    best_loss = None

    # Generating data
    images_and_labels = generate_data(trial)

    # Normalising images and labels
    images_scaler = utils.DynamicMinMaxScaler()
    labels_scaler = utils.DynamicMinMaxScaler()

    logged_labels = np.array(images_and_labels["labels"])[:, 3:5]  # Select the electron parameters
    logged_labels[:, 1] = np.log10(logged_labels[:, 1])  # Logging E_N0 param

    images = images_scaler.fit_transform(np.array(images_and_labels["images"]))
    labels = labels_scaler.fit_transform(np.array(logged_labels))

    # Splitting into training and validation data
    N_TRAIN = (len(images) * 3) // 4
    train_images = images[:N_TRAIN]
    train_labels = labels[:N_TRAIN]
    test_images = images[N_TRAIN:]
    test_labels = labels[N_TRAIN:]

    # Training Model
    BATCH_SIZE = 32
    MAX_EPOCHS = 1000
    PATIENCE = 15
    loss, model = ml_trial(
        train_images,
        train_labels,
        test_images,
        test_labels,
        BATCH_SIZE,
        MAX_EPOCHS,
        patience=PATIENCE,
    )

    # Updating if this is a new best trial
    if best_loss is None or loss < best_loss:
        best_loss = loss
        best_attributes["images_and_labels"] = images_and_labels
        best_attributes["model"] = model

    return loss


def main() -> None:
    utils.create_output_dirs()

    # Deleting any existing dbs with the same name
    if os.path.exists(study_db_path):
        os.remove(study_db_path)

    study = optuna.create_study(
        direction="minimize",
        study_name=study_name,
        storage=f"sqlite:///{study_db_path}",
    )
    best_attributes = {"images_and_labels": None, "model": None}
    study.optimize(lambda trial: objective(trial, best_attributes), timeout=TIMEOUT)

    # Saving the best images and labels
    with open(best_images_and_labels_path, "wb") as file:
        pickle.dump(best_attributes["images_and_labels"], file)
        
    # Saving the best model
    best_attributes["model"].save(best_model_path)


if __name__ == "__main__":
    main()